# Generated by Adjutant

BUILD_DIR = {{data.BUILD_PATH}}

# find all templates
TPL_DIR = {{data.TEMPLATE_PATH}}
TPL_SRCS = $(shell find ${TPL_DIR} -type f -name '*.tpl')
# compile templates to python files
TPL_PYS = $(patsubst ${TPL_DIR}/%.tpl, $(BUILD_DIR)/__template__/%.tpl.py, $(TPL_SRCS))


all: $(TPL_PYS)

# compile templates to python files
$(BUILD_DIR)/__template__/%.tpl.py: ${TPL_DIR}/%.tpl
	adjutant template:compile $< -o $@
